### PR TITLE
Translate strings to Turkish

### PR DESCRIPTION
**Pull request by Alperen-Ozturk**
Translated app to Turkish language.

### CODE REVIEW

**Comment by Akilesh-T** [comment]
There are few more strings left out. Can you add those too? Thanks for the PR :)

**Comment by Alperen-Ozturk** [comment]
Done. (i guess)

**Comment by Akilesh-T** [comment]
> Done. (i guess)

There are few more. [Check here](https://github.com/Akilesh-T/ACC/blob/master/app/src/main/res/values/strings.xml)

**Comment by Alperen-Ozturk** [comment]
Done. (again)

**Pull request merged**
